print("Enter first digit")
a = ("Enter first digit")
a = int(input())
print("Enter second digit")
b = ("Enter second digit")
b = int(input())
print ("answer is")
print ( a+b )
print ("sucessfull made by Nitish Sushant Khrolia")